default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: swnyk_development

test:
  <<: *default
  database: swnyk_test

production:
  <<: *default
  database: swnyk_production
